# Finite Element Method

In [26]:
import numpy as np
from scipy import linalg

In [27]:
u0 = 0
uN = 1
N = 4 # the number of the interior node
h = (uN - u0) / N 

In [28]:
print(h)

0.25


In [29]:
estiff = [[1/h, -1/h],[-1/h, 1/h]]

In [30]:
print (estiff)

[[4.0, -4.0], [-4.0, 4.0]]


In [31]:
A = np.zeros([N+1, N+1])
RHS = np.zeros([N+1,1])
for i in range(1, N+1):
    A[i,i] += 1/h
    A[i-1, i-1] += 1/h
    A[i-1,i] += -1/h
    A[i,i-1] += -1/h
    RHS[i] += (h/2)
    RHS[i-1] += (h/2)
    print(i)
print(A)
print(RHS)

1
2
3
4
[[ 4. -4.  0.  0.  0.]
 [-4.  8. -4.  0.  0.]
 [ 0. -4.  8. -4.  0.]
 [ 0.  0. -4.  8. -4.]
 [ 0.  0.  0. -4.  4.]]
[[0.125]
 [0.25 ]
 [0.25 ]
 [0.25 ]
 [0.125]]


In [32]:
u = np.zeros([N+1,1])

In [33]:
# 处理边界条件
# 先更新右端项
print(RHS)
RHS[0] = 0
print(RHS)
    
# 更改矩阵A
for i in range(N+1):
    A[0,i] = 0
    A[i,0] = 0
A[0,0] = 1
print(A)

[[0.125]
 [0.25 ]
 [0.25 ]
 [0.25 ]
 [0.125]]
[[0.   ]
 [0.25 ]
 [0.25 ]
 [0.25 ]
 [0.125]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  8. -4.  0.  0.]
 [ 0. -4.  8. -4.  0.]
 [ 0.  0. -4.  8. -4.]
 [ 0.  0.  0. -4.  4.]]


In [34]:
x = linalg.solve(A, RHS)
print(x)

[[0.     ]
 [0.21875]
 [0.375  ]
 [0.46875]
 [0.5    ]]


In [36]:
for i in range(N+1):
    u[i] = (-1) * 0.5 *(i * h) * (i * h) + (i * h)
print(u)

[[0.     ]
 [0.21875]
 [0.375  ]
 [0.46875]
 [0.5    ]]
