# Finite Element Method

In [11]:
import numpy as np
from scipy import linalg

In [100]:
u0 = 0
uN = 1
N = 10 # the number of the interior node
h = (uN - u0) / N 

In [101]:
print(h)

0.1


In [102]:
estiff = [[1/h, -1/h],[-1/h, 1/h]]

In [103]:
print (estiff)

[[10.0, -10.0], [-10.0, 10.0]]


In [104]:
A = np.zeros([N+1, N+1])
RHS = np.zeros([N+1,1])
for i in range(1, N+1):
    A[i,i] += 1/h
    A[i-1, i-1] += 1/h
    A[i-1,i] += -1/h
    A[i,i-1] += -1/h
    RHS[i] += (h/2)
    RHS[i-1] += (h/2)
    print(i)
print(A)
print(RHS)

1
2
3
4
5
6
7
8
9
10
[[ 10. -10.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [-10.  20. -10.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. -10.  20. -10.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. -10.  20. -10.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. -10.  20. -10.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. -10.  20. -10.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. -10.  20. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -10.  20. -10.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. -10.  20. -10.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -10.  20. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. -10.  10.]]
[[0.05]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.05]]


In [105]:
u = np.zeros([N+1,1])

In [106]:
# 处理边界条件
# 先更新右端项
print(RHS)
for i in range(1,N):
    print(A[i,N])
    RHS[i] = RHS[i] - A[i,N]* (-0.5)
RHS[0] = 0
RHS[N] = -0.5
print(RHS)
    
# 更改矩阵A
for i in range(N+1):
    A[0,i] = 0
    A[i,0] = 0
    A[N,i] = 0
    A[i,N] = 0
A[0,0] = 1
A[N,N] = 1
print(A)

[[0.05]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.05]]
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
-10.0
[[ 0. ]
 [ 0.1]
 [ 0.1]
 [ 0.1]
 [ 0.1]
 [ 0.1]
 [ 0.1]
 [ 0.1]
 [ 0.1]
 [-4.9]
 [-0.5]]
[[  1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  20. -10.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. -10.  20. -10.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. -10.  20. -10.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. -10.  20. -10.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. -10.  20. -10.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. -10.  20. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -10.  20. -10.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. -10.  20. -10.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -10.  20.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.]]


In [107]:
x = linalg.solve(A, RHS)
print(x)

[[ 0.   ]
 [-0.005]
 [-0.02 ]
 [-0.045]
 [-0.08 ]
 [-0.125]
 [-0.18 ]
 [-0.245]
 [-0.32 ]
 [-0.405]
 [-0.5  ]]


In [108]:
for i in range(N+1):
    u[i] = (-1) * 0.5 *(i * h) * (i * h)
print(u)

[[-0.   ]
 [-0.005]
 [-0.02 ]
 [-0.045]
 [-0.08 ]
 [-0.125]
 [-0.18 ]
 [-0.245]
 [-0.32 ]
 [-0.405]
 [-0.5  ]]
