# Finite Element Method

In [108]:
import numpy as np
from scipy import linalg

In [109]:
u0 = 0
uN = 1
N = 2 # the number of the interior node
h = (uN - u0) / N 

In [110]:
print(h)

0.5


In [111]:
estiff = [[1/h, -1/h],[-1/h, 1/h]]

In [112]:
print (estiff)

[[2.0, -2.0], [-2.0, 2.0]]


In [133]:
A = np.zeros([N+1, N+1])
RHS = np.zeros([N+1,1])
for i in range(1, N):
    A[i,i] += 1/h
    A[i-1, i-1] += 1/h
    A[i-1,i] += -1/h
    A[i,i-1] += -1/h
    RHS[i] += (h/2)
    RHS[i-1] += (h/2)
    print(i)
A[0,0] += 1/h
RHS[0] += (h/2)
print(A)
print(RHS)

1
[[ 4. -2.  0.]
 [-2.  2.  0.]
 [ 0.  0.  0.]]
[[0.5 ]
 [0.25]
 [0.  ]]


In [134]:
u = np.zeros([N+1,1])

In [135]:
# 处理边界条件
# 先更新右端项
print(RHS)
for i in range(1,N):
    print(A[i,N])
    RHS += - A[i,N]* (-0.5)
print(RHS)
RHS[0] = 0
RHS[N] = -0.5
print(RHS)
    
# 更改矩阵A
for i in range(N+1):
    A[0,i] = 0
    A[i,0] = 0
    A[N,i] = 0
    A[i,N] = 0
A[0,0] = 1
A[N,N] = 1
print(A)

[[0.5 ]
 [0.25]
 [0.  ]]
0.0
[[0.5 ]
 [0.25]
 [0.  ]]
[[ 0.  ]
 [ 0.25]
 [-0.5 ]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]


In [136]:
x = linalg.solve(A, RHS)
print(x)

[[ 0.   ]
 [ 0.125]
 [-0.5  ]]


In [137]:
for i in range(N+1):
    u[i] = (-1) * 0.5 *(i * h) * (i * h)
print(u)

[[-0.   ]
 [-0.125]
 [-0.5  ]]
